security:
  jwt:
    secret-key: Z2FicmllbCB0cmFiYWxobyBkZSBjb25jbHVjYW8gZGUgY2x1c28=
    expiration-time: -1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
